solido:
    cors:
        max_age: 3600
        allow_headers:
            - Accept
            - Authorization
            - Content-Type
            - X-Order
            - Range

        expose_headers:
            - X-Total-Count
            - X-Continuation-Token

    dto:
        namespaces:
            - 'App\DTO'

    serializer:
        catch_exceptions: true

when@test:
    solido:
        test: ~
