services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/DTO/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\DTO\:
        resource: '../src/DTO/'
        shared: false
